In [3]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
plt.style.use('fivethirtyeight')
%matplotlib inline
%config InlineBackend.figure_format = 'svg'

In [10]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [15]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [14]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [17]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [18]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [19]:
b1 = a.reshape(2, -1)
b1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [20]:
b2 = a.reshape(3, -1)
b2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [21]:
b3 = a.reshape(4, -1)
b3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [22]:
b4 = a.reshape(-1, 3)
b4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [23]:
b5 = a.reshape(-1, 2)
b5

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [47]:
array = np.random.randn(3, 4)
flat_array = array.flatten()
print(flat_array.size, array.size)

12 12


In [72]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [73]:
b = np.array([[i] for i in range(20, 1, -2)])
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

In [92]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [97]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [103]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [104]:
A.shape, At.shape

((4, 3), (3, 4))

In [107]:
B = np.dot(A, At)
B, B.shape

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]), (4, 4))

In [109]:
np.linalg.det(B)

0.0

In [129]:
np.random.seed(42)
c = np.random.randint(0, 16, 16)
c

array([ 6,  3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4])

In [132]:
row_num = np.sqrt(c.size)
C = c.reshape(int(row_num), -1)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [135]:
D = np.add(B, np.dot(C, 10))
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [140]:
np.linalg.det(D)

-28511999.999999944

In [142]:
np.linalg.matrix_rank(D)

4

In [155]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

In [156]:
for i in range(D_inv.shape[0]):
    for j in range(D_inv.shape[1]):
        if D_inv[i][j] <= 0:
            D_inv[i][j] = 0
        else:
            D_inv[i][j] = 1
D_inv

array([[1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [163]:
E = np.where(D_inv, B, C)
print(E)
print()
print(D_inv)
print()
print(B)
print()
print(C)

[[  5  14  23  14]
 [ 10   7  12 122]
 [  6   9   2 212]
 [ 32  10 212   4]]

[[1. 1. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 1. 0.]]

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]

[[ 6  3 12 14]
 [10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]]
